---
- name: Update and upgrade packages (apt)
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  tags:
    - update

- name: Update and upgrade packages (dnf)
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags:
    - update
